### ISSUE TITLE
Add a blank line before and after a list of books

### ISSUE THREAD

**Issue by Anachronaut** [Anachronaut/readinglist#1]
In the ui.py show_books function, print a blank line before and after the list of books, or the 'no books' message.

**Comment by Anachronaut** [comment]
Added code to ui.py, @crantz007 please check the blank_line branch for the updated code

**Comment by crantz007** [comment]
@Anachronaut  OK I'm working on it to update the code

**Comment by Anachronaut** [comment]
@crantz007 I already updated this code, I just need you to check it

**Comment by Anachronaut** [comment]
Branch merged
