### ISSUE TITLE
Should delete should be a method of the Book class, not Bookstore?

### ISSUE THREAD

**Issue by claraj** [Anachronaut/readinglist#11]
In the same way that save is a method of the Book class
Methods that operate on one Book should belong to the Book class
Methods that operate on the book store as a collection, belong to bookstore?

**Comment by Anachronaut** [comment]
@claraj I think I did this right. Please check the delete_book branch for a delete(self) function in the Book class in bookstore.py.

**Comment by Anachronaut** [comment]
Branch merged
